# Generated by Django 5.0 on 2024-03-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_package_tags_alter_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimages',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='core.package'),
        ),
    ]
