# Generated by Django 5.0 on 2024-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_packageimages_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_count',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_life_date',
            field=models.CharField(blank=True, default='100 Days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
