# Generated by Django 5.0 on 2024-03-03 03:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_package_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is a Package.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
