# Generated by Django 5.0.1 on 2024-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_package_package_date_from_package_package_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
