# Generated by Django 5.0.1 on 2024-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Gandhinagar', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Gujarat', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, default='382870', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
